AirHelp/eventboss

Gemfile.lock, bin/eventboss, lib/eventboss/version.rb
Due to a changes introduced in Rails 6 regarding autoloading we need to determine how to perform eager_load. Please check https://weblog.rubyonrails.org/2019/2/22/zeitwerk-integration-in-rails-6-beta-2/ for more details.
=> Use zeitwerk if possible

lib/eventboss/configuration.rb, lib/eventboss/version.rb, spec/eventboss/configuration_spec.rb
SInce eventboss might have a different configuration on different environments we do want to have the ability to skip rising the exception on missing configuration directly from ENV variable (not only from the initializer which is the same for all the environments).
Introducting `EVENTBUS_RAISE_ON_MISSING_CONFIGURATION` ENV flag for it.
=> Expose raise_on_missing_configuration in ENV

lib/eventboss/version.rb, lib/tasks/eventboss.rake
We don't need this suffix "-" in source_app when we combine queue_name with .join("-")
=> Fix: reload rake task - removed additional suffix "-"

README.md, lib/eventboss/railtie.rb, lib/tasks/eventboss.rake, spec/eventboss/configuration_spec.rb
I've been trying to run `eventboss:deadletter:reload` rake and ended up with `The specified queue does not exist for this wsdl version`. After some investigation I figured out that my initializer is not loaded before running rake. With missing configuration queue name was wrongly build. 
- Added `compact` before joining in queue_name generation 
In case of generic queue (without source_app) queue_name would end up with two dashes in a row
- Added environment loading to reload task if `Rails` is defined + description how to handle it in non Rails app (while using config files)
- Improved one of configuration specs to properly use value from each loop
=> Load environment in reload task

Gemfile.lock, eventboss.gemspec, lib/eventboss.rb, lib/eventboss/launcher.rb
Eventboss manages its own threads pool/state, no need to include it.
Only drawback was to know minimum number of workers, however this variable is configured by `concurrency` setting anyway.
=> Drop dependency on concurrent-ruby

lib/eventboss/scripts.rb
We should not define a rake task if there's no rake
=> Rake should be optional

lib/eventboss/listener.rb, lib/eventboss/queue_listener.rb, spec/eventboss/listener_spec.rb, spec/eventboss/queue_listener_spec.rb
I've hit 80 characters queue size limit. So I've decided to migrate application name to short one (long-name-application => LNA). During the migration I need to listen on queues with both app names such as:
```
long-name-application-eventboss-source_app-event_name-production
lna-eventboss-source_app-event_name-production
```
Right now it's not possible using eventboss. That's why I'm introducing `destination_app` option in listener.
=> Add destination_app option to listener eventboss_options

Gemfile.lock, bin/eventboss, lib/eventboss/version.rb
I've removed `STDOUT.sync=true` by mistake, while adding Cli class in https://github.com/AirHelp/eventboss/pull/32
=> Bring back STDOUT.sync

lib/eventboss/launcher.rb, lib/eventboss/long_poller.rb, lib/eventboss/unit_of_work.rb, lib/eventboss/worker.rb, spec/eventboss/unit_of_work_spec.rb, spec/eventboss/worker_spec.rb
1. Simplify the interface of Worker a bit, removing the dependency of the `client`
2. Allow configuring `error` that triggers the restart of the worker, mostly to simplify tests
=> Refactor worker

Gemfile.lock, README.md, lib/eventboss.rb, lib/eventboss/configuration.rb, lib/eventboss/development_mode.rb, lib/eventboss/error_handlers/logger.rb, lib/eventboss/listener.rb, lib/eventboss/publisher.rb, lib/eventboss/queue.rb, lib/eventboss/queue_listener.rb, lib/eventboss/runner.rb, lib/eventboss/sns_client.rb, lib/eventboss/topic.rb, lib/eventboss/version.rb, spec/eventboss/configuration_spec.rb, spec/eventboss/development_mode_spec.rb, spec/eventboss/fetcher_spec.rb, spec/eventboss/listener_spec.rb, spec/eventboss/publisher_spec.rb, spec/eventboss/queue_listener_spec.rb, spec/eventboss/queue_spec.rb, spec/eventboss/runner_spec.rb, spec/eventboss/sns_client_spec.rb, spec/eventboss/topic_spec.rb, spec/eventboss_spec.rb
When developing an application with Eventboss one might want to test if processing messages works as expected.
Currently it requires creating needed AWS infrastructure beforehand, either through AWS IAM, via a CLI or terraform setup. 
This extra step makes for a not so smooth development experience. 
This can be mitigated by creating a setup script that creates and links required SNSes & SQSes, e.g.
https://gist.github.com/przprz/e6a445865fcfdeacb44be7186f99c498
Such a script works fine in an environment with a relaxed infrastructure policy, such as development env.  
But if the environment allows to create SNS/SQS through a script, it could as well set it up on the fly without creating a dedicated script.
This is what we call the _development mode_.
=> Add development mode

Gemfile.lock, lib/eventboss/version.rb, lib/generators/eventboss/listener/eventboss_listener.rb.erb, lib/generators/eventboss/listener/listener_generator.rb
Generating code is so much fun.
How about generating Eventboss listener boilerplate instead of creating it manually or copypasting?\*
Just type:
```sh
rails g eventboss:listener get_well air-helper
```
To get:
```ruby
class GetWellListener
include Eventboss::Listener
eventboss_options event_name: 'get_well', source_app: 'air-helper'
def receive(payload)
Rails.logger.tagged(jid) { Rails.logger.info("payload: #{ payload }") }
end
end
```
\*so far Rails version only.
[//]: # (#### Includes:)
[//]: # (#### Related Links)
[//]: # (#### ah-config)
[//]: # (#### Related PRs)
[//]: # (#### Description)
[//]: # (#### Additional deploy notes)
[//]: # (#### Does this change any URL Paths?)
[//]: # (#### Screenshots)
=> Add listener generator

Gemfile.lock, lib/eventboss/configuration.rb, lib/eventboss/error_handlers/db_connection_not_established_handler.rb, lib/eventboss/extensions.rb, lib/eventboss/version.rb, spec/eventboss/error_handlers/db_connection_not_established_handler_spec.rb
Some time ago Legal Claim Cases started throwing errors like the following one: https://errbit.ahinternal.net/apps/5936b9e1d3a45600060071fc/problems/5f1979691ce8520007ee6333
We could not identify the root cause of the problem and it just went away after a few hours.
This PR is an attempt to address it - whenever such error occurs again the app will try to reconnect to the database.
=> Add ActiveRecord::ConnectionNotEstablished handler

Gemfile.lock, lib/eventboss/error_handlers/rollbar.rb, lib/eventboss/extensions.rb, lib/eventboss/version.rb, spec/eventboss/error_handlers/rollbar_handler_spec.rb
To make the Rollbar integration easier for applications leveraging Eventboss.
=> Add a Rollbar error handler

lib/eventboss/launcher.rb, lib/eventboss/long_poller.rb, lib/eventboss/worker.rb, spec/eventboss/long_poller_spec.rb
This PR prevents deadlock during shutdown. It seems to only appear when `worker_count` is significantly higher than `@bus` size, which is around 100.
```
INFO -- launcher: Starting 100 workers, 2 pollers
(... worker does its job ...)
INFO -- runner: Received SIGTERM signal, gracefully shutting down...
INFO -- launcher: Gracefully shutdown
INFO -- launcher: Waiting for 1 pollers, 36 workers
INFO -- launcher: Waiting for 0 pollers, 36 workers
INFO -- launcher: Waiting for 0 pollers, 36 workers
INFO -- launcher: Waiting for 0 pollers, 36 workers
INFO -- launcher: Waiting for 0 pollers, 36 workers
INFO -- launcher: Killing remaining 0 pollers, 36 workers
bundler: failed to load command: eventboss (/usr/local/bundle/bin/eventboss)
fatal: No live threads left. Deadlock?
10 threads, 10 sleeps …
```
=> Deadlock fix during shutdown

lib/eventboss/error_handlers/rollbar.rb, spec/eventboss/error_handlers/rollbar_handler_spec.rb
What
Since we use `Rollbar.error` to handle all exceptions that reach eventboss we want to respect setting https://docs.rollbar.com/docs/ruby#section-exception-level-filters
Why
To be able to ignore/filter exceptions that are raised in eventboss instance.
=> Respect exception filters in rollbar handler

CHANGELOG.md, Gemfile.lock, eventboss.gemspec, lib/eventboss/cli.rb, lib/eventboss/version.rb
Right now, we can't upgrade `dotenv` because of a gem conflict. So, instead of just loosening the dependency, I decided to cut it out completely. That said, if `dotenv` is around, our app will happily load it up.
This aspec was previously brought up [here](https://github.com/AirHelp/eventboss/pull/32#discussion_r337854261)
I don't know about what versions should it be/who should change it, so happy to hear how to do it
=> Drop dotenv

lib/eventboss/launcher.rb
The message about the launcher being gracefully shut down is logged before it actually occurs, which may lead to some confusion. This PR simply rearranges the order of the messages.
=> Update reporting about shutting down

lib/eventboss/launcher.rb
Because of this SIGTERM signal is not handled correctly and alert is pushed to SMS and slack channels
=> BINGO fix typo in isntance var during shut down

lib/eventboss/configuration.rb, lib/eventboss/sns_client.rb
Credentials for SQS and SNS are being hardcoded for a specific credential method, and it does not work with new IAM roles.
In case the credentials are unspecified, AWS should try to select one of the available options.
https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/SQS/Client.html#initialize-instance_method
I've thought that for now it would be safer to change this behind env variable (even if most probably it still would work without it right now). At the end if we all use IAM Roles, we can just get rid of the credentials at all. Or allow in app initializer to define it's own credentials instance
=> Allow to use default credentials for SNS and SQS clients

CHANGELOG.md, README.md, eventboss.gemspec, lib/eventboss/error_handlers/sentry.rb, lib/eventboss/long_poller.rb, lib/eventboss/publisher.rb, lib/eventboss/sentry/configure.rb, lib/eventboss/sentry/context.rb, lib/eventboss/sentry/error_handler.rb, lib/eventboss/sentry/integration.rb, lib/eventboss/sentry/server_middleware.rb, lib/eventboss/version.rb, spec/eventboss/long_poller_spec.rb, spec/eventboss/publisher_spec.rb
This PR introduces Sentry for Eventboss with performance monitoring, distributed tracing, and enhanced error reporting.
The new `Eventboss::Sentry::ServerMiddleware` creates transactions for message processing witg context (queue names, message IDs, latency, retry counts)
Simple one-line setup via `require 'eventboss/sentry/configure'` automatically configures both client and server components. The old Eventboss::ErrorHandlers::Sentry is deprecated
To see it working please see: https://airhelp.sentry.io/insights/backend/queues/?environment=staging&project=4506716776693760&statsPeriod=1h
This branch is currently on staging & production. The staging has newest version deployed ~1h ago
This middleware is based on [sidekiq integration …
=> Add sentry middleware

CHANGELOG.md, lib/eventboss/publisher.rb, lib/eventboss/version.rb
Fixes [undefined method 'set_data' for nil (NoMethodError) span.set_data](https://airhelp.sentry.io/issues/6823402020/?alert_rule_id=14996423&alert_type=issue&environment=staging&notification_uuid=d542bf41-e4bb-4b54-a13b-fc00418e056f&project=4506716776693760&referrer=slack)  
Also in [sidekiq integration](https://github.com/getsentry/sentry-ruby/blob/master/sentry-sidekiq/lib/sentry/sidekiq/sentry_context_middleware.rb#L9) there are checks if it's nil
=> [ROMEO-457] Fix NoMethodError in sentry integration
